#!/bin/sh
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.cache/zsh/history
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.local/share/go/bin:$PATH
# export PATH=$HOME/.cargo/bin:$PATH
# export GOPATH=$HOME/.local/share/go
# export PATH=$HOME/.miniconda/bin:$PATH

# eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

