#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" 

# get fastest mirrors
alias \
    mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" \
    mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist" \
    mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist" \
    mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist" 

# These common commands are just too long! Abbreviate them.
	# ka="killall" \
	# g="git" \
	# trem="transmission-remote" \
	# xi="sudo xbps-install" \
	# xr="sudo xbps-remove -R" \
	# xq="xbps-query" \

	# magit="nvim -c MagitOnly" \
	# ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	# weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	# tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
alias \
	f="$FILE" \
	e="$EDITOR" \
	p="sudo pacman" \
	cat="bat" \
	ls="exa --icons --group-directories-first" \
	la="exa -lha --icons --group-directories-first" \
	t="trans :id" \
	te="trans :en" \
	unrar="unrar x" \
	k="ps -u $USER k -size -o %mem=,%cpu=,comm= |dmenu -i -l 15 |awk '{print $1}'" \
	yt="ytfzf -t" \
	yta="ytfzf -tm" \
	ytd="ytfzf -df" \
	ytr="ytfzf -r" \
	ttq="curl http://api.quotable.io/random|jq '[.text=.content|.attribution=.author]'|tt -quotes -" \
    config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' \
    topdf="libreoffice --headless --invisible --convert-to pdf" \
    bagi='curl -F"file=@$(find $pwd -type f | fzf)" 0x0.st' \
    tte="tt -quotes en" \
